# Generated by Django 3.2.7 on 2021-09-18 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='PublicDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 18, 17, 13, 35, 37, tzinfo=utc)),
        ),
    ]
